sudo: required
services: 
  - docker

before_install:
  - docker build -t grumpywolf7/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true grumpywolf7/react-test npm test

after_success: 
  - docker build -t grumpywolf7/multi-client ./client
  - docker build -t grumpywolf7/multi-nginx ./nginx
  - docker build -t grumpywolf7/multi-server ./server
  - docker build -t grumpywolf7/multi-worker ./worker
  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images to docker hub
  - docker push grumpywolf7/multi-client
  - docker push grumpywolf7/multi-nginx
  - docker push grumpywolf7/multi-server
  - docker push grumpywolf7/multi-worker
